name: Module 1 homework

on: [push, pull_request]

jobs:
  removeVowels:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir module1/homework/removeVowels/build
      run: mkdir module1/homework/removeVowels/build
    - name: Compile
      working-directory: module1/homework/removeVowels/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: module1/homework/removeVowels/build
      run: ctest -V

  lengthSort:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir module1/homework/lengthSort/build
      run: mkdir module1/homework/lengthSort/build
    - name: Compile
      working-directory: module1/homework/lengthSort/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: module1/homework/lengthSort/build
      run: ctest -V

  grayscaleImages:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir module1/homework/grayscaleImages/build
      run: mkdir module1/homework/grayscaleImages/build
    - name: Compile
      working-directory: module1/homework/grayscaleImages/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: module1/homework/grayscaleImages/build
      run: ctest -V
